const images = {
  landingImage: require('../assets/Image/landingImage.jpg'),
  iconLanding: require('../assets/Image/maps.png'),
  loginIcon: require('../assets/Image/login.png'),
  viewPassword: require('../assets/Image/view.png'),
  hidePassword: require('../assets/Image/hidden.png'),
  homeActive: require('../assets/Image/house-active.png'),
  homeInactive: require('../assets/Image/house-inactive.png'),
  savedActive: require('../assets/Image/saved-active.png'),
  savedInactive: require('../assets/Image/saved-inactive.png'),
  settingInactive: require('../assets/Image/setting.png'),
  settingActive: require('../assets/Image/setting-active.png'),
  searchIcon: require('../assets/Image/loupe-white.png'),
  mountainsImg: require('../assets/Image/mountains.png'),
  villaImg: require('../assets/Image/villa.png'),
  cafeImg: require('../assets/Image/coffee.png'),
  hotelImg: require('../assets/Image/hotel.png'),
  fitnesImg: require('../assets/Image/fitness.png'),
  grandPadis: require('../assets/Image/grandPadis.jpg'),
  heartImg: require('../assets/Image/heart.png'),
  ArrowBack: require('../assets/Image/ArrowBack.png'),
  locationIcon: require('../assets/Image/location.png'),
};

export default images;
